apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: docker.io/bitpoke/wordpress-operator
    docker:
      dockerfile: hack/Dockerfile.skaffold
deploy:
  helm:
    releases:
    - name: wp-operator
      chartPath: deploy/charts/wordpress-operator
      setValues:
        imagePullPolicy: Always
      valuesFiles:
        - hack/skaffold-values.yaml
      values:
        image: docker.io/bitpoke/wordpress-operator

